// Mock dataset search results for Storybook stories
// Simulates the response from the /search/ API endpoint

export const mockDatasets = {
  'dataset-1': {
    identifier: 'dataset-1',
    title: 'Medicare Provider Utilization and Payment Data',
    description: 'Provider-level data on services and procedures provided to Medicare beneficiaries.',
    modified: '2024-03-15T14:30:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
      format: 'csv',
      downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-1.csv',
      describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-1-dd.json',
      describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-2': {
    identifier: 'dataset-2',
    title: 'Hospital Compare National Data',
    description: 'National-level data on hospital quality measures and patient outcomes.',
    modified: '2024-03-10T09:15:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-2.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-2-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-3': {
    identifier: 'dataset-3',
    title: 'Medicare Part D Prescriber Data',
    description: 'Prescriber-level Medicare Part D claims data including drug costs and utilization.',
    modified: '2024-03-05T16:45:00',
    theme: ['Prescription Drugs'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-3.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-3-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-4': {
    identifier: 'dataset-4',
    title: 'Nursing Home Compare Data',
    description: 'Quality ratings and inspection results for Medicare-certified nursing homes.',
    modified: '2024-02-28T11:20:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-4.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-4-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-5': {
    identifier: 'dataset-5',
    title: 'Home Health Compare Data',
    description: 'Quality of care data for home health agencies serving Medicare patients.',
    modified: '2024-02-25T13:10:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-5.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-5-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-6': {
    identifier: 'dataset-6',
    title: 'Medicare Inpatient Hospitals Data',
    description: 'Inpatient prospective payment system hospital charge and payment data.',
    modified: '2024-02-20T10:05:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-6.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-6-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-7': {
    identifier: 'dataset-7',
    title: 'Physician Compare National Downloadable File',
    description: 'Information on physicians and other healthcare professionals enrolled in Medicare.',
    modified: '2024-02-15T14:55:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-7.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-7-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-8': {
    identifier: 'dataset-8',
    title: 'Medicare Outpatient Hospitals Data',
    description: 'Outpatient prospective payment system hospital charge and payment data.',
    modified: '2024-02-10T08:30:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-8.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-8-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-9': {
    identifier: 'dataset-9',
    title: 'Medicare Spending Per Beneficiary',
    description: 'Spending data per Medicare beneficiary at the hospital and state level.',
    modified: '2024-02-05T15:25:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-9.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-9-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-10': {
    identifier: 'dataset-10',
    title: 'Hospital Readmissions Reduction Program',
    description: 'Data on hospital readmission rates and payment adjustments under HRRP.',
    modified: '2024-01-30T12:40:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-10.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-10-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-11': {
    identifier: 'dataset-11',
    title: 'Medicare Advantage Enrollment Data',
    description: 'Monthly enrollment data for Medicare Advantage and Part D plans.',
    modified: '2024-01-25T09:50:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-11.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-11-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-12': {
    identifier: 'dataset-12',
    title: 'Medicare Part D Drug Spending',
    description: 'Drug spending and utilization data for the Medicare Part D program.',
    modified: '2024-01-20T16:15:00',
    theme: ['Prescription Drugs', 'Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-12.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-12-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-13': {
    identifier: 'dataset-13',
    title: 'Medicare Fee-for-Service Provider Data',
    description: 'Fee-for-service claims data summarized at the provider level.',
    modified: '2024-01-15T11:35:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-13.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-13-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-14': {
    identifier: 'dataset-14',
    title: 'Medicare Geographic Variation Data',
    description: 'Geographic variation in Medicare spending, utilization, and quality.',
    modified: '2024-01-10T14:20:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-14.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-14-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-15': {
    identifier: 'dataset-15',
    title: 'Medicare Chronic Conditions Data',
    description: 'Prevalence and spending data for chronic conditions among Medicare beneficiaries.',
    modified: '2024-01-05T10:45:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-15.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-15-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-16': {
    identifier: 'dataset-16',
    title: 'Medicare Beneficiary Summary File',
    description: 'Summary demographic and enrollment data for Medicare beneficiaries.',
    modified: '2023-12-30T13:55:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-16.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-16-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-17': {
    identifier: 'dataset-17',
    title: 'Medicare Provider Enrollment Data',
    description: 'Data on providers and suppliers enrolled in the Medicare program.',
    modified: '2023-12-25T09:30:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-17.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-17-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-18': {
    identifier: 'dataset-18',
    title: 'Medicare Claims Data',
    description: 'Aggregated Medicare claims data across inpatient, outpatient, and physician services.',
    modified: '2023-12-20T15:10:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-18.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-18-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-19': {
    identifier: 'dataset-19',
    title: 'Medicare Quality Measures Data',
    description: 'Quality performance measures for Medicare-participating providers.',
    modified: '2023-12-15T11:25:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-19.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-19-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-20': {
    identifier: 'dataset-20',
    title: 'Medicare Cost Report Data',
    description: 'Annual cost report data submitted by Medicare-certified institutional providers.',
    modified: '2023-12-10T08:40:00',
    theme: ['Medicare'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-20.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-20-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-21': {
    identifier: 'dataset-21',
    title: 'Medicare Shared Savings Program Data',
    description: 'Performance and financial data for accountable care organizations in MSSP.',
    modified: '2023-12-05T14:50:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-21.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-21-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-22': {
    identifier: 'dataset-22',
    title: 'Medicare Hospital Value-Based Purchasing',
    description: 'Hospital performance scores and payment adjustments under the VBP program.',
    modified: '2023-11-30T10:15:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-22.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-22-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-23': {
    identifier: 'dataset-23',
    title: 'Medicare Ambulatory Surgical Center Data',
    description: 'Quality measures and payment data for ambulatory surgical centers.',
    modified: '2023-11-25T16:30:00',
    theme: ['Hospital Quality'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-23.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-23-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-24': {
    identifier: 'dataset-24',
    title: 'Medicare Dialysis Facility Compare Data',
    description: 'Quality ratings and clinical data for Medicare-certified dialysis facilities.',
    modified: '2023-11-20T12:45:00',
    theme: ['Prescription Drugs'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-24.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-24-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
  'dataset-25': {
    identifier: 'dataset-25',
    title: 'Medicare Hospice Compare Data',
    description: 'Quality measures and survey data for Medicare-certified hospice providers.',
    modified: '2023-11-15T09:20:00',
    theme: ['Prescription Drugs'],
    distribution: [{
      title: 'CSV Download',
        format: 'csv',
        downloadURL: 'https://data.cms.gov/provider-data/sites/default/files/resources/dataset-25.csv',
        describedBy: 'https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/dataset-25-dd.json',
        describedByType: 'application/vnd.tableschema+json',
    }],
  },
};

export const mockApiResponse = {
  total: 25,
  results: mockDatasets,
};

export const mockSmallDatasetList = {
  total: 3,
  results: {
    'dataset-1': mockDatasets['dataset-1'],
    'dataset-2': mockDatasets['dataset-2'],
    'dataset-3': mockDatasets['dataset-3'],
  },
};

export const mockEmptyResults = {
  total: 0,
  results: {},
};

export const mockFacets = [
  { type: 'theme', name: 'Medicare', total: '12' },
  { type: 'theme', name: 'Hospital Quality', total: '8' },
  { type: 'theme', name: 'Prescription Drugs', total: '5' },
  { type: 'keyword', name: '2024', total: '10' },
  { type: 'keyword', name: '2023', total: '15' },
];

export const mockApiResponseWithFacets = {
  total: 25,
  results: mockDatasets,
  facets: mockFacets,
};
